<?php 
class Command
{
	var $VIRTUAL_ACCOUNT_REGIST_REQUEST = "0100"; // 가상계좌 등록 요청
	var $VIRTUAL_ACCOUNT_REGIST_RESPONSE = "0101"; // 가상계좌 등록 응답
	var $DEMAND_REGIST_REQUEST = "0200"; // 청구데이터 등록 요청
	var $DEMAND_REGIST_RESPONSE = "0201"; // 청구데이터 등록 응답
	var $DEMAND_REGIST_WITH_ACCOUNT_REQUEST = "0210"; // 청구데이터  가상계좌지정 등록 요청
	var $DEMAND_REGIST_WITH_ACCOUNT_RESPONSE = "0211"; // 청구데이터  가상계좌지정 등록  응답
	var $DEMAND_REGIST_AND_ACCOUNT_REGIST_REQUEST = "0220"; // 청구데이터  등록 및 가상계좌 등록 요청
	var $DEMAND_REGIST_AND_ACCOUNT_REGIST_RESPONSE = "0221"; // 청구데이터 등록 및 가상계좌 등록  응답
	var $DEMAND_REGIST_WITH_DEMAND_GROUP_REQUEST = "0230"; // 청구데이터  등록 [청구그룹별 등록] 요청
	var $DEMAND_REGIST_WITH_DEMAND_GROUP_RESPONSE = "0231"; // 청구데이터 등록 [청구그룹별 등록] 응답
  var $TEST_CALL_REQUEST = "0300";  // 테스트콜 요청
	var $TEST_CALL_RESPONSE = "0301"; // 테스트콜 응답
  var $INQUIRY_REQUEST = "1000"; // 조회 요청
	var $INQUIRY_RESPONSE = "1001"; // 조회 응답
	var $PIN_INQUIRY_REQUEST = "1010"; // 핀 조회 요청
	var $PIN_INQUIRY_RESPONSE = "1011"; // 핀 조회 응답
	var $ACCOUNT_PAYMENT_INQUIRY_REQUEST = "1100"; // 가상계좌 수납여부 조회 요청
	var $ACCOUNT_PAYMENT_INQUIRY_RESPONSE = "1101"; // 가상계좌 수납여부 조회  응답
  var $ID_INQUIRY_REQUEST = "1020"; // ID 조회 요청
	var $ID_INQUIRY_RESPONSE = "1021"; // ID 조회 응답
  var $CERTIFY_REQUEST = "2000"; // 인증 요청
	var $CERTIFY_RESPONSE = "2001"; // 인증 응답
  var $AUTO_BILL_CERTIFY_REQUEST = "2100"; // 자동과금 인증 요청
	var $AUTO_BILL_CERTIFY_RESPONSE = "2101"; // 자동과금 인증 요청 응답
  var $IDENTITY_CERTIFY_REQUEST = "2110"; // 본인인증 요청
	var $IDENTITY_CERTIFY_RESPONSE = "2111"; // 본인인증  요청  응답
  var $AUTO_BILL_AGREE_CERTIFY_REQUEST = "2120"; // 자동과금  동의 인증 요청
	var $AUTO_BILL_AGREE_CERTIFY_RESPONSE = "2121"; // 자동과금 동의 인증  요청  응답
  var $ID_CERTIFY_REQUEST = "2010"; // ID 인증 요청
	var $ID_CERTIFY_RESPONSE = "2011"; // ID 인증 응답
  var $CERTIFY_SMS_REQUEST = "2200"; // 인증 SMS 재 전송 요청
	var $CERTIFY_SMS_RESPONSE = "2201"; // 인증 SMS 재 전송 요청 응답
	var $ARS_CERTIFY_REQUEST = "2300"; // ARS데몬 인증 요청
	var $ARS_CERTIFY_RESPONSE = "2301"; // ARS데몬 인증 요청 응답
  var $AUTH_REQUEST = "3000"; // 승인 요청
	var $AUTH_RESPONSE = "3001"; // 승인 응답 
  var $ID_AUTH_REQUEST = "3010"; // ID 승인 요청
	var $ID_AUTH_RESPONSE = "3011"; // ID 승인 응답
  var $AUTO_BILL_AUTH_REQUEST = "3020"; // 자동과금 승인 요청
	var $AUTO_BILL_AUTH_RESPONSE = "3021"; // 자동과금 승인 응답
	var $AUTO_BILL_AGREE_AUTH_REQUEST = "3030"; // 자동 과금  동의 승인 요청
	var $AUTO_BILL_AGREE_AUTH_RESPONSE = "3031"; // 자동 과금 동의 승인 응답
  var $CERTIFY_AUTH_REQUEST = "3040" ; // 인증 및 승인 요청
	var $CERTIFY_AUTH_RESPONSE = "3041" ; // 인증 및 승인 응
  var $ID_CERTIFY_AUTH_REQUEST = "3050"; // 아이디  인증/승인 요청
	var $ID_CERTIFY_AUTH_RESPONSE = "3051"; // 아이디 인증/승인 응답
  var $PIN_CERTIFY_AUTH_REQUEST = "3060"; //핀  인증/승인 요청
	var $PIN_CERTIFY_AUTH_RESPONSE = "3061"; //핀  인증/승인 응
  var $IDENTITY_CONFIRM_REQUEST = "3110"; // 본인인증 확인 요청
	var $IDENTITY_CONFIRM_RESPONSE = "3111"; // 본인인증  확인 요청  응답
  var $BILL_REQUEST = "3900"; // 최종 과금 요청
	var $BILL_RESPONSE = "3901"; // 최종 과금 응답
  var $AUTO_BILL_AGREE_BILL_REQUEST = "3910"; // 자동 과금  동의 과금 요청
	var $AUTO_BILL_AGREE_BILL_RESPONSE = "3911"; // 자동 과금 동의 과금 응답
	var $ALARM_REQUEST = "4000" ; // 알람 요청 
	var $ALARM_RESPONSE = "4001" ; // 알람 요청 응답
	var $AUTH_MAIL_REQUEST = "4010"; // 승인 메일 요청
	var $AUTH_MAIL_RESPONSE = "4011"; // 승인 메일 요청 응답
  var $AUTH_QUERY_REQUEST = "5000"; // 승인 내역 조회 요청
	var $AUTH_QUERY_RESPONSE = "5001"; // 승인 내역 조회 응답
  var $CERTIFY_QUERY_REQUEST = "5100"; // 인증 결과 확인 요청
	var $CERTIFY_QUERY_RESPONSE = "5101"; // 인증 결과 확인 요청 응답
  var $SUM_QUERY_REQUEST = "5200"; // 집계 결과 확인 요청
	var $SUM_QUERY_RESPONSE = "5201"; // 집계 결과 확인 요청 응답
  var $JOB_START_REQUEST = "6100";  // 업무개시 요청
	var $JOB_START_RESPONSE = "6101"; // 업무개시 응답
  var $JOB_END_REQUEST = "6200";  // 업무종료 요청
	var $JOB_END_RESPONSE = "6201"; // 업무종료 응답
  var $DEMAND_UPDATE_REQUEST = "8000"; // 청구데이터  수정 요청
	var $DEMAND_UPDATE_RESPONSE = "8001"; // 청구데이터  수정  응답
	var $VIRTUAL_ACCOUNT_UPDATE_REQUEST = "8010"; // 가상계좌  수정 요청
	var $VIRTUAL_ACCOUNT_UPDATE_RESPONSE = "8011"; // 가상계좌  수정  응답
	var $REFUND_SMS_REQUEST 		= "8100"; // 환불 SMS 요청
	var $REFUND_SMS_RESPONSE 		= "8101"; // 환불 SMS 응답
	var $CANCEL_REQUEST = "9000"; // 취소 요청
	var $CANCEL_RESPONSE = "9001"; // 취소 응답
	var $CANCEL_ADMIN_REQUEST = "9010"; // 취소 요청 [관리자용]
	var $CANCEL_ADMIN_RESPONSE = "9011"; // 취소 응답 [관리자용]
  var $NETWORK_CANCEL_REQUEST = "9100"; // 망 취소 요청
	var $NETWORK_CANCEL_RESPONSE = "9101"; // 망 취소 응답
	var $CANCEL_SMS_REQUEST 		= "9200"; // SMS 취소 요청
	var $CANCEL_SMS_RESPONSE 		= "9201"; // SMS 취소 응답
	var $BUY_CANCEL_REQUEST 		= "9300"; // 매입 취소 요청
	var $BUY_CANCEL_RESPONSE 		= "9301"; // 매입 취소 응답 
  var $CASHRECEIPT_REQUEST = "3200"; // 현금영수증 데이터등록 요청
	var $CASHRECEIPT_RESPONSE = "3201"; // 현금영수증 데이터등록 요청 응답
  var $CASHRECEIPT_BATCH_REQUEST = "3210"; // 현금영수증 데이터 파일 등록 요청
	var $CASHRECEIPT_BATCH_RESPONSE = "3211"; // 현금영수증 데이터  파일 등록 요청  응답
  var $CASHRECEIPT_RESULT_REQUEST = "3220"; // 현금영수증 처리결과 데이터 파일 요청
	var $CASHRECEIPT_RESULT_RESPONSE = "3221"; // 현금영수증 처리결과 데이터 파일 요청 응답
}
?>